In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [2]:
data = pd.read_csv("./utils/mitsubishi_imiev.csv", encoding='latin-1')
avg_speed = pd.read_csv('./utils/volkswagen_e_golf.csv')
avg_speed
data.shape

(1285, 20)

In [3]:
data.drop('avg_speed(km/h)', axis=1, inplace=True)
a = avg_speed["avg_speed(km/h)"].loc[0:1285]
data = pd.concat([data, a], axis=1)
data

manufacturer   model version  power(kW)   fuel_date  odometer  \
0      Mitsubishi  i-MiEV  i-MiEV       49.0  07.02.2019  176977.0   
1      Mitsubishi  i-MiEV  i-MiEV       49.0  06.02.2019  176926.0   
2      Mitsubishi  i-MiEV  i-MiEV       49.0  05.02.2019  176876.0   
3      Mitsubishi  i-MiEV  i-MiEV       49.0  04.02.2019  176824.0   
4      Mitsubishi  i-MiEV  i-MiEV       49.0  03.02.2019  176772.0   
...           ...     ...     ...        ...         ...       ...   
1281   Mitsubishi  i-MiEV  i-MiEV       49.0  23.08.2016  115089.0   
1282   Mitsubishi  i-MiEV  i-MiEV       49.0  23.08.2016  115077.0   
1283   Mitsubishi  i-MiEV  i-MiEV       49.0  23.08.2016  115048.0   
1284   Mitsubishi  i-MiEV  i-MiEV       49.0  23.08.2016  114952.0   
1285          NaN     NaN     NaN        NaN         NaN       NaN   

      trip_distance(km)  quantity(kWh)    fuel_type     tire_type  city  \
0                  50.7           6.50  Electricity  Winter tires   1.0   
1                  49.9           7.30  Electricity  Winter tires   1.0   
2                  51.5           7.10  Electricity  Winter tires   1.0   
3                  52.5           7.40  Electricity  Winter tires   1.0   
4                   0.5           1.65  Electricity  Winter tires   1.0   
...                 ...            ...          ...           ...   ...   
1281               12.4           5.68  Electricity  Summer tires   1.0   
1282               29.3           4.00  Electricity  Summer tires   1.0   
1283               95.2           5.25  Electricity  Summer tires   0.0   
1284               45.5          10.40  Electricity  Summer tires   0.0   
1285                NaN            NaN          NaN           NaN   NaN   

      motor_way  country_roads driving_style  consumption(kWh/100km)  A/C  \
0           0.0            1.0        Normal                     NaN  0.0   
1           0.0            1.0        Normal                   14.63  0.0   
2           0.0            1.0        Normal                   13.79  0.0   
3           0.0            1.0        Normal                   14.10  0.0   
4           0.0            0.0        Normal                   14.47  0.0   
...         ...            ...           ...                     ...  ...   
1281        0.0            1.0        Normal                   10.91  0.0   
1282        0.0            1.0        Normal                   10.91  1.0   
1283        1.0            1.0        Normal                   10.91  1.0   
1284        1.0            1.0        Normal                   12.64  0.0   
1285        NaN            NaN           NaN                     NaN  NaN   

      park_heating  ecr_deviation  \
0              0.0            NaN   
1              0.0          -0.37   
2              0.0          -1.21   
3              0.0          -0.90   
4              0.0          -0.53   
...            ...            ...   
1281           0.0          -4.09   
1282           0.0          -4.09   
1283           0.0          -4.09   
1284           0.0          -2.36   
1285           NaN            NaN   

                                              fuel_note  avg_speed(km/h)  
0     Noch 6 Balken, 33km Reichweite, Mainova Ökostr...             53.0  
1     Noch 5 Balken, 30km Reichweite, Mainova Ökostr...             47.0  
2     Noch 6B, 36km RRW, Batterie 8-11°C, 9,3°C, 41,...             58.0  
3     Noch 5 Balken, 30km Reichweite, Mainova Ökostr...             43.0  
4     Noch 15 Balken, 75km Reichweite, 85,5%, Batter...             76.0  
...                                                 ...              ...  
1281  Noch 10 Balken, 81km Reichweite, 2,75h geladen...             27.0  
1282  Noch 6 Balken, 49km Reichweite, 44,0%, Batteri...             48.0  
1283  Noch 4 Balken, 26km Reichweite, 29,5%, Batteri...             28.0  
1284  Noch 4 Balken, 27km Reichweite, 31,0%, Batteri...             41.0  
1285                                                NaN             

In [4]:
data.isnull().sum()

manufacturer               1
model                      1
version                    1
power(kW)                  1
fuel_date                  1
odometer                   1
trip_distance(km)          1
quantity(kWh)             40
fuel_type                  1
tire_type                  1
city                       1
motor_way                  1
country_roads              1
driving_style              1
consumption(kWh/100km)    52
A/C                        1
park_heating               1
ecr_deviation             52
fuel_note                  2
avg_speed(km/h)            9
dtype: int64

In [5]:
data.dropna(inplace=True)

In [6]:
data.drop(['manufacturer', 'model', 'fuel_type', 'version', 'fuel_note', 'power(kW)'], axis=1, inplace=True)

In [7]:
data.dtypes

fuel_date                  object
odometer                  float64
trip_distance(km)         float64
quantity(kWh)             float64
tire_type                  object
city                      float64
motor_way                 float64
country_roads             float64
driving_style              object
consumption(kWh/100km)    float64
A/C                       float64
park_heating              float64
ecr_deviation             float64
avg_speed(km/h)           float64
dtype: object

In [8]:
data.fuel_date = pd.to_datetime(data.fuel_date)

/home/shin0bi/miniconda3/envs/ev-analysis/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.01.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/home/shin0bi/miniconda3/envs/ev-analysis/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '30.01.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/home/shin0bi/miniconda3/envs/ev-analysis/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '28.01.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/home/shin0bi/miniconda3/envs/ev-analysis/lib/python3.9/site-packages/pandas/co

In [9]:
data

fuel_date  odometer  trip_distance(km)  quantity(kWh)     tire_type  \
1    2019-06-02  176926.0               49.9           7.30  Winter tires   
2    2019-05-02  176876.0               51.5           7.10  Winter tires   
3    2019-04-02  176824.0               52.5           7.40  Winter tires   
4    2019-03-02  176772.0                0.5           1.65  Winter tires   
5    2019-03-02  176771.0               15.4           6.50  Winter tires   
...         ...       ...                ...            ...           ...   
1280 2016-08-24  115172.0               82.8           9.90  Summer tires   
1281 2016-08-23  115089.0               12.4           5.68  Summer tires   
1282 2016-08-23  115077.0               29.3           4.00  Summer tires   
1283 2016-08-23  115048.0               95.2           5.25  Summer tires   
1284 2016-08-23  114952.0               45.5          10.40  Summer tires   

      city  motor_way  country_roads driving_style  consumption(kWh/100km)  \
1      1.0        0.0            1.0        Normal                   14.63   
2      1.0        0.0            1.0        Normal                   13.79   
3      1.0        0.0            1.0        Normal                   14.10   
4      1.0        0.0            0.0        Normal                   14.47   
5      1.0        0.0            1.0        Normal                   14.47   
...    ...        ...            ...           ...                     ...   
1280   1.0        0.0            1.0        Normal                   11.96   
1281   1.0        0.0            1.0        Normal                   10.91   
1282   1.0        0.0            1.0        Normal                   10.91   
1283   0.0        1.0            1.0        Normal                   10.91   
1284   0.0        1.0            1.0        Normal                   12.64   

      A/C  park_heating  ecr_deviation  avg_speed(km/h)  
1     0.0           0.0          -0.37             47.0  
2     0.0           0.0          -1.21             58.0  
3     0.0           0.0          -0.90             43.0  
4     0.0           0.0          -0.53             76.0  
5     0.0           0.0          -0.53             23.0  
...   ...           ...            ...              ...  
1280  1.0           0.0          -3.04             45.0  
1281  0.0           0.0          -4.09             27.0  
1282  1.0           0.0          -4.09             48.0  
1283  1.0           0.0          -4.09             28.0  
1284  0.0           0.0          -2.36             41.0  

[1224 rows x 14 columns]

In [10]:
data.fuel_date = pd.to_numeric(pd.to_datetime(data.fuel_date))

In [11]:
data = pd.get_dummies(data, drop_first=True)

In [12]:
from sklearn.model_selection import train_test_split
X = data.drop('consumption(kWh/100km)', axis=1)
y = data["consumption(kWh/100km)"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) 

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.fit_transform(X_test)



In [14]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

lr.fit(X_train, y_train)

predictions = lr.predict(X_test)

In [15]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
print(r2_score(y_test, predictions))
print(mean_squared_error(y_test, predictions))

0.999836819998006
0.0003604319884042782


In [16]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

svm_preds = regressor.predict(X_test)

In [17]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
print(r2_score(y_test, svm_preds))
print(mean_squared_error(y_test, svm_preds))

0.9498344422196902
0.11080568402514841


In [18]:
from sklearn.linear_model import SGDRegressor
reg = SGDRegressor()
reg.fit(X_train, y_train)
sgd_preds = reg.predict(X_test)

In [19]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
print(r2_score(y_test, sgd_preds))
print(mean_squared_error(y_test, sgd_preds))

0.9994323557633138
0.0012538125899924423


In [20]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor()
knn.fit(X_train, y_train)
knn_preds = knn.predict(X_test)

In [21]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
print(r2_score(y_test, knn_preds))
print(mean_squared_error(y_test, knn_preds))

0.8326579470614759
0.3696251265306122


In [22]:
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import DotProduct, WhiteKernel
kernel = DotProduct() + WhiteKernel()
gpr = GaussianProcessRegressor(kernel=kernel)
gpr.fit(X_train, y_train)
gpr_preds = reg.predict(X_test)


In [23]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
print(r2_score(y_test, gpr_preds))
print(mean_squared_error(y_test, gpr_preds))

0.9994323557633138
0.0012538125899924423


In [24]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()
dtr.fit(X_train, y_train)
dtr_preds = dtr.predict(X_test)

In [25]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
print(r2_score(y_test, dtr_preds))
print(mean_squared_error(y_test, dtr_preds))

0.9984898994005426
0.0033355102040816286


In [26]:
pickle.dump(dtr, open('model.pkl', 'wb'))

In [27]:
data

fuel_date  odometer  trip_distance(km)  quantity(kWh)  city  \
1     1559433600000000000  176926.0               49.9           7.30   1.0   
2     1556755200000000000  176876.0               51.5           7.10   1.0   
3     1554163200000000000  176824.0               52.5           7.40   1.0   
4     1551484800000000000  176772.0                0.5           1.65   1.0   
5     1551484800000000000  176771.0               15.4           6.50   1.0   
...                   ...       ...                ...            ...   ...   
1280  1471996800000000000  115172.0               82.8           9.90   1.0   
1281  1471910400000000000  115089.0               12.4           5.68   1.0   
1282  1471910400000000000  115077.0               29.3           4.00   1.0   
1283  1471910400000000000  115048.0               95.2           5.25   0.0   
1284  1471910400000000000  114952.0               45.5          10.40   0.0   

      motor_way  country_roads  consumption(kWh/100km)  A/C  park_heating  \
1           0.0            1.0                   14.63  0.0           0.0   
2           0.0            1.0                   13.79  0.0           0.0   
3           0.0            1.0                   14.10  0.0           0.0   
4           0.0            0.0                   14.47  0.0           0.0   
5           0.0            1.0                   14.47  0.0           0.0   
...         ...            ...                     ...  ...           ...   
1280        0.0            1.0                   11.96  1.0           0.0   
1281        0.0            1.0                   10.91  0.0           0.0   
1282        0.0            1.0                   10.91  1.0           0.0   
1283        1.0            1.0                   10.91  1.0           0.0   
1284        1.0            1.0                   12.64  0.0           0.0   

      ecr_deviation  avg_speed(km/h)  tire_type_Winter tires  \
1             -0.37             47.0                       1   
2             -1.21             58.0                       1   
3             -0.90             43.0                       1   
4             -0.53             76.0                       1   
5             -0.53             23.0                       1   
...             ...              ...                     ...   
1280          -3.04             45.0                       0   
1281          -4.09             27.0                       0   
1282          -4.09             48.0                       0   
1283          -4.09             28.0                       0   
1284          -2.36             41.0                       0   

      driving_style_Moderate  driving_style_Normal  
1                          0                     1  
2                          0                     1  
3                          0                     1  
4                          0                     1  
5                          0                     1  
...                      ...                   ...  
1280                       0                     1  
1281                       0                     1  
1282                       0                     1  
1283                       0                     1  
1284                       0                     1  

[1224 rows x 15 columns]

In [28]:
data.dtypes

fuel_date                   int64
odometer                  float64
trip_distance(km)         float64
quantity(kWh)             float64
city                      float64
motor_way                 float64
country_roads             float64
consumption(kWh/100km)    float64
A/C                       float64
park_heating              float64
ecr_deviation             float64
avg_speed(km/h)           float64
tire_type_Winter tires      uint8
driving_style_Moderate      uint8
driving_style_Normal        uint8
dtype: object

In [29]:
x2 = np.array([1471910400000000000, 114952.0, 45.5, 10.40 ,0.0 ,1.0 ,1.0 ,0.0 ,0.0 ,-2.36 ,41.0 ,0 ,0 ,1])
x2 = x2.reshape(1, -1)
scaler.fit_transform(x2)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
dtr.predict(x2)

array([9.59])

In [31]:
lr.predict(x2)

array([1245.81659463])

In [32]:
gpr.predict(x2)

array([-6.23436849e+14])

In [33]:
regressor.predict(x2)

array([12.80665437])

In [34]:
reg.predict(x2)

array([-7.23339033e+16])

In [35]:
knn.predict(x2)

array([12.36])